# Generated by Django 3.1.2 on 2020-12-19 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gkmitApp.accounts')),
            ],
        ),
    ]
