# Generated by Django 3.1.2 on 2020-12-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0002_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
