# Generated by Django 3.1.2 on 2020-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0004_auto_20201219_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.UUIDField(default=105808828116052480777193531522506225824, editable=False, unique=True),
        ),
    ]
