# Generated by Django 3.1.2 on 2020-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0005_auto_20201219_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.UUIDField(default=336617777448502759314325215188791637835, editable=False, unique=True),
        ),
    ]
