# Generated by Django 3.1.2 on 2020-12-19 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0006_auto_20201219_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.CharField(default=uuid.UUID('9e0611b7-9ca2-4aa5-a9a0-4559839ede08'), editable=False, max_length=18, unique=True),
        ),
    ]
