# Generated by Django 3.1.2 on 2020-12-20 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0007_auto_20201219_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.CharField(default=uuid.UUID('4f045bac-1637-4827-9469-a356bfe8a956'), editable=False, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
