# Generated by Django 3.1.2 on 2020-12-20 08:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gkmitApp', '0008_auto_20201220_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_id',
            field=models.CharField(default=uuid.UUID('a093e2fe-403d-4703-a666-00ca065b517d'), editable=False, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
